### PR TITLE
update

### PR DESCRIPTION
**Pull request by mninc**
remove redundant dependency

### CODE REVIEW

**Comment by Sakuya-Izayoi** [comment]
merge dis

**Comment by Sakuya-Izayoi** [comment]
merge dis x2

**Comment by WolfMountainGames** [comment]
Wow, I have not checked this in a long time. 
I merged it, thanks for the update.

**Comment by MrSchiavon** [comment]
hi, plz check the config.admin, i already put the SteamID64 and still the error continues..

Stack: ReferenceError: admin is not defined
    at SteamUser.<anonymous> (C:\Users\TioDavi\Desktop\tf2-autoprice-bot-master\daemon_shop.js:664:35)
    at emitTwo (events.js:126:13)
    at SteamUser.emit (events.js:214:7)
    at SteamUser._emitIdEvent (C:\Users\TioDavi\node_modules\steam-user\components\utility.js:29:12)
    at SteamUser._handlers.(anonymous function) (C:\Users\TioDavi\node_modules\steam-user\components\chat.js:281:9)
    at SteamUser._handleMessage (C:\Users\TioDavi\node_modules\steam-user\components\messages.js:249:30)
    at emitThree (events.js:136:13)
    at CMClient.emit (events.js:217:7)
    at CMClient._netMsgReceived (C:\Users\TioDavi\node_modules\steam-client\lib\cm_client.js:323:8)
    at CMClient.handlers.(anonymous function) (C:\Users\TioDavi\node_modules\steam-client\lib\cm_client.js:603:8)
EXIT

**Pull request merged**
